package cn.lby.mapper;

import cn.lby.entity.Appointment;
import cn.lby.entity.AppointmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppointmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int countByExample(AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int deleteByExample(AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int insert(Appointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int insertSelective(Appointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	List<Appointment> selectByExampleWithBLOBs(AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	List<Appointment> selectByExample(AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	Appointment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Appointment record,
			@Param("example") AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") Appointment record,
			@Param("example") AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Appointment record,
			@Param("example") AppointmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Appointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Appointment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Appointment record);
}