package cn.lby.mapper;

import cn.lby.entity.AppointmentLoginManage;
import cn.lby.entity.AppointmentLoginManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppointmentLoginManageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int countByExample(AppointmentLoginManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int deleteByExample(AppointmentLoginManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String mobile);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int insert(AppointmentLoginManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int insertSelective(AppointmentLoginManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	List<AppointmentLoginManage> selectByExample(
			AppointmentLoginManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	AppointmentLoginManage selectByPrimaryKey(String mobile);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record") AppointmentLoginManage record,
			@Param("example") AppointmentLoginManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AppointmentLoginManage record,
			@Param("example") AppointmentLoginManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AppointmentLoginManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment_login_manage
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AppointmentLoginManage record);
}