package cn.lby.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppointmentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table appointment
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table appointment
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table appointment
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public AppointmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appointment
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table appointment
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdIsNull() {
			addCriterion("market_activity_id is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdIsNotNull() {
			addCriterion("market_activity_id is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdEqualTo(String value) {
			addCriterion("market_activity_id =", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotEqualTo(String value) {
			addCriterion("market_activity_id <>", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdGreaterThan(String value) {
			addCriterion("market_activity_id >", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdGreaterThanOrEqualTo(String value) {
			addCriterion("market_activity_id >=", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdLessThan(String value) {
			addCriterion("market_activity_id <", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdLessThanOrEqualTo(String value) {
			addCriterion("market_activity_id <=", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdLike(String value) {
			addCriterion("market_activity_id like", value, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotLike(String value) {
			addCriterion("market_activity_id not like", value,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdIn(List<String> values) {
			addCriterion("market_activity_id in", values, "marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotIn(List<String> values) {
			addCriterion("market_activity_id not in", values,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdBetween(String value1, String value2) {
			addCriterion("market_activity_id between", value1, value2,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityIdNotBetween(String value1,
				String value2) {
			addCriterion("market_activity_id not between", value1, value2,
					"marketActivityId");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeIsNull() {
			addCriterion("market_activity_code is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeIsNotNull() {
			addCriterion("market_activity_code is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeEqualTo(String value) {
			addCriterion("market_activity_code =", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotEqualTo(String value) {
			addCriterion("market_activity_code <>", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeGreaterThan(String value) {
			addCriterion("market_activity_code >", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeGreaterThanOrEqualTo(String value) {
			addCriterion("market_activity_code >=", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeLessThan(String value) {
			addCriterion("market_activity_code <", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeLessThanOrEqualTo(String value) {
			addCriterion("market_activity_code <=", value, "marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeLike(String value) {
			addCriterion("market_activity_code like", value,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotLike(String value) {
			addCriterion("market_activity_code not like", value,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeIn(List<String> values) {
			addCriterion("market_activity_code in", values,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotIn(List<String> values) {
			addCriterion("market_activity_code not in", values,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeBetween(String value1,
				String value2) {
			addCriterion("market_activity_code between", value1, value2,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityCodeNotBetween(String value1,
				String value2) {
			addCriterion("market_activity_code not between", value1, value2,
					"marketActivityCode");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartIsNull() {
			addCriterion("market_activity_start is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartIsNotNull() {
			addCriterion("market_activity_start is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartEqualTo(Date value) {
			addCriterion("market_activity_start =", value,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartNotEqualTo(Date value) {
			addCriterion("market_activity_start <>", value,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartGreaterThan(Date value) {
			addCriterion("market_activity_start >", value,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartGreaterThanOrEqualTo(Date value) {
			addCriterion("market_activity_start >=", value,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartLessThan(Date value) {
			addCriterion("market_activity_start <", value,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartLessThanOrEqualTo(Date value) {
			addCriterion("market_activity_start <=", value,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartIn(List<Date> values) {
			addCriterion("market_activity_start in", values,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartNotIn(List<Date> values) {
			addCriterion("market_activity_start not in", values,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartBetween(Date value1, Date value2) {
			addCriterion("market_activity_start between", value1, value2,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityStartNotBetween(Date value1,
				Date value2) {
			addCriterion("market_activity_start not between", value1, value2,
					"marketActivityStart");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndIsNull() {
			addCriterion("market_activity_end is null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndIsNotNull() {
			addCriterion("market_activity_end is not null");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndEqualTo(Date value) {
			addCriterion("market_activity_end =", value, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndNotEqualTo(Date value) {
			addCriterion("market_activity_end <>", value, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndGreaterThan(Date value) {
			addCriterion("market_activity_end >", value, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndGreaterThanOrEqualTo(Date value) {
			addCriterion("market_activity_end >=", value, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndLessThan(Date value) {
			addCriterion("market_activity_end <", value, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndLessThanOrEqualTo(Date value) {
			addCriterion("market_activity_end <=", value, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndIn(List<Date> values) {
			addCriterion("market_activity_end in", values, "marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndNotIn(List<Date> values) {
			addCriterion("market_activity_end not in", values,
					"marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndBetween(Date value1, Date value2) {
			addCriterion("market_activity_end between", value1, value2,
					"marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andMarketActivityEndNotBetween(Date value1, Date value2) {
			addCriterion("market_activity_end not between", value1, value2,
					"marketActivityEnd");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNull() {
			addCriterion("customer_id is null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIsNotNull() {
			addCriterion("customer_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerIdEqualTo(String value) {
			addCriterion("customer_id =", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotEqualTo(String value) {
			addCriterion("customer_id <>", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThan(String value) {
			addCriterion("customer_id >", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
			addCriterion("customer_id >=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThan(String value) {
			addCriterion("customer_id <", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLessThanOrEqualTo(String value) {
			addCriterion("customer_id <=", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdLike(String value) {
			addCriterion("customer_id like", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotLike(String value) {
			addCriterion("customer_id not like", value, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdIn(List<String> values) {
			addCriterion("customer_id in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotIn(List<String> values) {
			addCriterion("customer_id not in", values, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdBetween(String value1, String value2) {
			addCriterion("customer_id between", value1, value2, "customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerIdNotBetween(String value1, String value2) {
			addCriterion("customer_id not between", value1, value2,
					"customerId");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIsNull() {
			addCriterion("customer_name is null");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIsNotNull() {
			addCriterion("customer_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerNameEqualTo(String value) {
			addCriterion("customer_name =", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotEqualTo(String value) {
			addCriterion("customer_name <>", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameGreaterThan(String value) {
			addCriterion("customer_name >", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
			addCriterion("customer_name >=", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLessThan(String value) {
			addCriterion("customer_name <", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLessThanOrEqualTo(String value) {
			addCriterion("customer_name <=", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameLike(String value) {
			addCriterion("customer_name like", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotLike(String value) {
			addCriterion("customer_name not like", value, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameIn(List<String> values) {
			addCriterion("customer_name in", values, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotIn(List<String> values) {
			addCriterion("customer_name not in", values, "customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameBetween(String value1, String value2) {
			addCriterion("customer_name between", value1, value2,
					"customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerNameNotBetween(String value1, String value2) {
			addCriterion("customer_name not between", value1, value2,
					"customerName");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileIsNull() {
			addCriterion("customer_mobile is null");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileIsNotNull() {
			addCriterion("customer_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileEqualTo(String value) {
			addCriterion("customer_mobile =", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotEqualTo(String value) {
			addCriterion("customer_mobile <>", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileGreaterThan(String value) {
			addCriterion("customer_mobile >", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileGreaterThanOrEqualTo(String value) {
			addCriterion("customer_mobile >=", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileLessThan(String value) {
			addCriterion("customer_mobile <", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileLessThanOrEqualTo(String value) {
			addCriterion("customer_mobile <=", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileLike(String value) {
			addCriterion("customer_mobile like", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotLike(String value) {
			addCriterion("customer_mobile not like", value, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileIn(List<String> values) {
			addCriterion("customer_mobile in", values, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotIn(List<String> values) {
			addCriterion("customer_mobile not in", values, "customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileBetween(String value1, String value2) {
			addCriterion("customer_mobile between", value1, value2,
					"customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerMobileNotBetween(String value1, String value2) {
			addCriterion("customer_mobile not between", value1, value2,
					"customerMobile");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailIsNull() {
			addCriterion("customer_email is null");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailIsNotNull() {
			addCriterion("customer_email is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailEqualTo(String value) {
			addCriterion("customer_email =", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotEqualTo(String value) {
			addCriterion("customer_email <>", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailGreaterThan(String value) {
			addCriterion("customer_email >", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailGreaterThanOrEqualTo(String value) {
			addCriterion("customer_email >=", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailLessThan(String value) {
			addCriterion("customer_email <", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailLessThanOrEqualTo(String value) {
			addCriterion("customer_email <=", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailLike(String value) {
			addCriterion("customer_email like", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotLike(String value) {
			addCriterion("customer_email not like", value, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailIn(List<String> values) {
			addCriterion("customer_email in", values, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotIn(List<String> values) {
			addCriterion("customer_email not in", values, "customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailBetween(String value1, String value2) {
			addCriterion("customer_email between", value1, value2,
					"customerEmail");
			return (Criteria) this;
		}

		public Criteria andCustomerEmailNotBetween(String value1, String value2) {
			addCriterion("customer_email not between", value1, value2,
					"customerEmail");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateIsNull() {
			addCriterion("appointment_date is null");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateIsNotNull() {
			addCriterion("appointment_date is not null");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateEqualTo(Date value) {
			addCriterion("appointment_date =", value, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateNotEqualTo(Date value) {
			addCriterion("appointment_date <>", value, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateGreaterThan(Date value) {
			addCriterion("appointment_date >", value, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateGreaterThanOrEqualTo(Date value) {
			addCriterion("appointment_date >=", value, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateLessThan(Date value) {
			addCriterion("appointment_date <", value, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateLessThanOrEqualTo(Date value) {
			addCriterion("appointment_date <=", value, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateIn(List<Date> values) {
			addCriterion("appointment_date in", values, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateNotIn(List<Date> values) {
			addCriterion("appointment_date not in", values, "appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateBetween(Date value1, Date value2) {
			addCriterion("appointment_date between", value1, value2,
					"appointmentDate");
			return (Criteria) this;
		}

		public Criteria andAppointmentDateNotBetween(Date value1, Date value2) {
			addCriterion("appointment_date not between", value1, value2,
					"appointmentDate");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdIsNull() {
			addCriterion("vehicle_model_id is null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdIsNotNull() {
			addCriterion("vehicle_model_id is not null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdEqualTo(String value) {
			addCriterion("vehicle_model_id =", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotEqualTo(String value) {
			addCriterion("vehicle_model_id <>", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdGreaterThan(String value) {
			addCriterion("vehicle_model_id >", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdGreaterThanOrEqualTo(String value) {
			addCriterion("vehicle_model_id >=", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdLessThan(String value) {
			addCriterion("vehicle_model_id <", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdLessThanOrEqualTo(String value) {
			addCriterion("vehicle_model_id <=", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdLike(String value) {
			addCriterion("vehicle_model_id like", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotLike(String value) {
			addCriterion("vehicle_model_id not like", value, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdIn(List<String> values) {
			addCriterion("vehicle_model_id in", values, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotIn(List<String> values) {
			addCriterion("vehicle_model_id not in", values, "vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdBetween(String value1, String value2) {
			addCriterion("vehicle_model_id between", value1, value2,
					"vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelIdNotBetween(String value1, String value2) {
			addCriterion("vehicle_model_id not between", value1, value2,
					"vehicleModelId");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeIsNull() {
			addCriterion("vehicle_model_code is null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeIsNotNull() {
			addCriterion("vehicle_model_code is not null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeEqualTo(String value) {
			addCriterion("vehicle_model_code =", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotEqualTo(String value) {
			addCriterion("vehicle_model_code <>", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeGreaterThan(String value) {
			addCriterion("vehicle_model_code >", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeGreaterThanOrEqualTo(String value) {
			addCriterion("vehicle_model_code >=", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeLessThan(String value) {
			addCriterion("vehicle_model_code <", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeLessThanOrEqualTo(String value) {
			addCriterion("vehicle_model_code <=", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeLike(String value) {
			addCriterion("vehicle_model_code like", value, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotLike(String value) {
			addCriterion("vehicle_model_code not like", value,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeIn(List<String> values) {
			addCriterion("vehicle_model_code in", values, "vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotIn(List<String> values) {
			addCriterion("vehicle_model_code not in", values,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeBetween(String value1, String value2) {
			addCriterion("vehicle_model_code between", value1, value2,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelCodeNotBetween(String value1,
				String value2) {
			addCriterion("vehicle_model_code not between", value1, value2,
					"vehicleModelCode");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameIsNull() {
			addCriterion("vehicle_model_name is null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameIsNotNull() {
			addCriterion("vehicle_model_name is not null");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameEqualTo(String value) {
			addCriterion("vehicle_model_name =", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotEqualTo(String value) {
			addCriterion("vehicle_model_name <>", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameGreaterThan(String value) {
			addCriterion("vehicle_model_name >", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameGreaterThanOrEqualTo(String value) {
			addCriterion("vehicle_model_name >=", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameLessThan(String value) {
			addCriterion("vehicle_model_name <", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameLessThanOrEqualTo(String value) {
			addCriterion("vehicle_model_name <=", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameLike(String value) {
			addCriterion("vehicle_model_name like", value, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotLike(String value) {
			addCriterion("vehicle_model_name not like", value,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameIn(List<String> values) {
			addCriterion("vehicle_model_name in", values, "vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotIn(List<String> values) {
			addCriterion("vehicle_model_name not in", values,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameBetween(String value1, String value2) {
			addCriterion("vehicle_model_name between", value1, value2,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andVehicleModelNameNotBetween(String value1,
				String value2) {
			addCriterion("vehicle_model_name not between", value1, value2,
					"vehicleModelName");
			return (Criteria) this;
		}

		public Criteria andDealerIdIsNull() {
			addCriterion("dealer_id is null");
			return (Criteria) this;
		}

		public Criteria andDealerIdIsNotNull() {
			addCriterion("dealer_id is not null");
			return (Criteria) this;
		}

		public Criteria andDealerIdEqualTo(String value) {
			addCriterion("dealer_id =", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotEqualTo(String value) {
			addCriterion("dealer_id <>", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdGreaterThan(String value) {
			addCriterion("dealer_id >", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdGreaterThanOrEqualTo(String value) {
			addCriterion("dealer_id >=", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdLessThan(String value) {
			addCriterion("dealer_id <", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdLessThanOrEqualTo(String value) {
			addCriterion("dealer_id <=", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdLike(String value) {
			addCriterion("dealer_id like", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotLike(String value) {
			addCriterion("dealer_id not like", value, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdIn(List<String> values) {
			addCriterion("dealer_id in", values, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotIn(List<String> values) {
			addCriterion("dealer_id not in", values, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdBetween(String value1, String value2) {
			addCriterion("dealer_id between", value1, value2, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerIdNotBetween(String value1, String value2) {
			addCriterion("dealer_id not between", value1, value2, "dealerId");
			return (Criteria) this;
		}

		public Criteria andDealerCodeIsNull() {
			addCriterion("dealer_code is null");
			return (Criteria) this;
		}

		public Criteria andDealerCodeIsNotNull() {
			addCriterion("dealer_code is not null");
			return (Criteria) this;
		}

		public Criteria andDealerCodeEqualTo(String value) {
			addCriterion("dealer_code =", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotEqualTo(String value) {
			addCriterion("dealer_code <>", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeGreaterThan(String value) {
			addCriterion("dealer_code >", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeGreaterThanOrEqualTo(String value) {
			addCriterion("dealer_code >=", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeLessThan(String value) {
			addCriterion("dealer_code <", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeLessThanOrEqualTo(String value) {
			addCriterion("dealer_code <=", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeLike(String value) {
			addCriterion("dealer_code like", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotLike(String value) {
			addCriterion("dealer_code not like", value, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeIn(List<String> values) {
			addCriterion("dealer_code in", values, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotIn(List<String> values) {
			addCriterion("dealer_code not in", values, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeBetween(String value1, String value2) {
			addCriterion("dealer_code between", value1, value2, "dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerCodeNotBetween(String value1, String value2) {
			addCriterion("dealer_code not between", value1, value2,
					"dealerCode");
			return (Criteria) this;
		}

		public Criteria andDealerNameIsNull() {
			addCriterion("dealer_name is null");
			return (Criteria) this;
		}

		public Criteria andDealerNameIsNotNull() {
			addCriterion("dealer_name is not null");
			return (Criteria) this;
		}

		public Criteria andDealerNameEqualTo(String value) {
			addCriterion("dealer_name =", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotEqualTo(String value) {
			addCriterion("dealer_name <>", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameGreaterThan(String value) {
			addCriterion("dealer_name >", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameGreaterThanOrEqualTo(String value) {
			addCriterion("dealer_name >=", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameLessThan(String value) {
			addCriterion("dealer_name <", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameLessThanOrEqualTo(String value) {
			addCriterion("dealer_name <=", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameLike(String value) {
			addCriterion("dealer_name like", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotLike(String value) {
			addCriterion("dealer_name not like", value, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameIn(List<String> values) {
			addCriterion("dealer_name in", values, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotIn(List<String> values) {
			addCriterion("dealer_name not in", values, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameBetween(String value1, String value2) {
			addCriterion("dealer_name between", value1, value2, "dealerName");
			return (Criteria) this;
		}

		public Criteria andDealerNameNotBetween(String value1, String value2) {
			addCriterion("dealer_name not between", value1, value2,
					"dealerName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdIsNull() {
			addCriterion("sale_consultant_id is null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdIsNotNull() {
			addCriterion("sale_consultant_id is not null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdEqualTo(String value) {
			addCriterion("sale_consultant_id =", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotEqualTo(String value) {
			addCriterion("sale_consultant_id <>", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdGreaterThan(String value) {
			addCriterion("sale_consultant_id >", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdGreaterThanOrEqualTo(String value) {
			addCriterion("sale_consultant_id >=", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdLessThan(String value) {
			addCriterion("sale_consultant_id <", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdLessThanOrEqualTo(String value) {
			addCriterion("sale_consultant_id <=", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdLike(String value) {
			addCriterion("sale_consultant_id like", value, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotLike(String value) {
			addCriterion("sale_consultant_id not like", value,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdIn(List<String> values) {
			addCriterion("sale_consultant_id in", values, "saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotIn(List<String> values) {
			addCriterion("sale_consultant_id not in", values,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdBetween(String value1, String value2) {
			addCriterion("sale_consultant_id between", value1, value2,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantIdNotBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_id not between", value1, value2,
					"saleConsultantId");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameIsNull() {
			addCriterion("sale_consultant_name is null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameIsNotNull() {
			addCriterion("sale_consultant_name is not null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameEqualTo(String value) {
			addCriterion("sale_consultant_name =", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotEqualTo(String value) {
			addCriterion("sale_consultant_name <>", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameGreaterThan(String value) {
			addCriterion("sale_consultant_name >", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameGreaterThanOrEqualTo(String value) {
			addCriterion("sale_consultant_name >=", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameLessThan(String value) {
			addCriterion("sale_consultant_name <", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameLessThanOrEqualTo(String value) {
			addCriterion("sale_consultant_name <=", value, "saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameLike(String value) {
			addCriterion("sale_consultant_name like", value,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotLike(String value) {
			addCriterion("sale_consultant_name not like", value,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameIn(List<String> values) {
			addCriterion("sale_consultant_name in", values,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotIn(List<String> values) {
			addCriterion("sale_consultant_name not in", values,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_name between", value1, value2,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantNameNotBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_name not between", value1, value2,
					"saleConsultantName");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileIsNull() {
			addCriterion("sale_consultant_mobile is null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileIsNotNull() {
			addCriterion("sale_consultant_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileEqualTo(String value) {
			addCriterion("sale_consultant_mobile =", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileNotEqualTo(String value) {
			addCriterion("sale_consultant_mobile <>", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileGreaterThan(String value) {
			addCriterion("sale_consultant_mobile >", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileGreaterThanOrEqualTo(String value) {
			addCriterion("sale_consultant_mobile >=", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileLessThan(String value) {
			addCriterion("sale_consultant_mobile <", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileLessThanOrEqualTo(String value) {
			addCriterion("sale_consultant_mobile <=", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileLike(String value) {
			addCriterion("sale_consultant_mobile like", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileNotLike(String value) {
			addCriterion("sale_consultant_mobile not like", value,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileIn(List<String> values) {
			addCriterion("sale_consultant_mobile in", values,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileNotIn(List<String> values) {
			addCriterion("sale_consultant_mobile not in", values,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_mobile between", value1, value2,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andSaleConsultantMobileNotBetween(String value1,
				String value2) {
			addCriterion("sale_consultant_mobile not between", value1, value2,
					"saleConsultantMobile");
			return (Criteria) this;
		}

		public Criteria andInfoSourceIsNull() {
			addCriterion("info_source is null");
			return (Criteria) this;
		}

		public Criteria andInfoSourceIsNotNull() {
			addCriterion("info_source is not null");
			return (Criteria) this;
		}

		public Criteria andInfoSourceEqualTo(Integer value) {
			addCriterion("info_source =", value, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceNotEqualTo(Integer value) {
			addCriterion("info_source <>", value, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceGreaterThan(Integer value) {
			addCriterion("info_source >", value, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceGreaterThanOrEqualTo(Integer value) {
			addCriterion("info_source >=", value, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceLessThan(Integer value) {
			addCriterion("info_source <", value, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceLessThanOrEqualTo(Integer value) {
			addCriterion("info_source <=", value, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceIn(List<Integer> values) {
			addCriterion("info_source in", values, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceNotIn(List<Integer> values) {
			addCriterion("info_source not in", values, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceBetween(Integer value1, Integer value2) {
			addCriterion("info_source between", value1, value2, "infoSource");
			return (Criteria) this;
		}

		public Criteria andInfoSourceNotBetween(Integer value1, Integer value2) {
			addCriterion("info_source not between", value1, value2,
					"infoSource");
			return (Criteria) this;
		}

		public Criteria andGiftIdIsNull() {
			addCriterion("gift_id is null");
			return (Criteria) this;
		}

		public Criteria andGiftIdIsNotNull() {
			addCriterion("gift_id is not null");
			return (Criteria) this;
		}

		public Criteria andGiftIdEqualTo(String value) {
			addCriterion("gift_id =", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdNotEqualTo(String value) {
			addCriterion("gift_id <>", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdGreaterThan(String value) {
			addCriterion("gift_id >", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdGreaterThanOrEqualTo(String value) {
			addCriterion("gift_id >=", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdLessThan(String value) {
			addCriterion("gift_id <", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdLessThanOrEqualTo(String value) {
			addCriterion("gift_id <=", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdLike(String value) {
			addCriterion("gift_id like", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdNotLike(String value) {
			addCriterion("gift_id not like", value, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdIn(List<String> values) {
			addCriterion("gift_id in", values, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdNotIn(List<String> values) {
			addCriterion("gift_id not in", values, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdBetween(String value1, String value2) {
			addCriterion("gift_id between", value1, value2, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftIdNotBetween(String value1, String value2) {
			addCriterion("gift_id not between", value1, value2, "giftId");
			return (Criteria) this;
		}

		public Criteria andGiftCodeIsNull() {
			addCriterion("gift_code is null");
			return (Criteria) this;
		}

		public Criteria andGiftCodeIsNotNull() {
			addCriterion("gift_code is not null");
			return (Criteria) this;
		}

		public Criteria andGiftCodeEqualTo(String value) {
			addCriterion("gift_code =", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeNotEqualTo(String value) {
			addCriterion("gift_code <>", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeGreaterThan(String value) {
			addCriterion("gift_code >", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeGreaterThanOrEqualTo(String value) {
			addCriterion("gift_code >=", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeLessThan(String value) {
			addCriterion("gift_code <", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeLessThanOrEqualTo(String value) {
			addCriterion("gift_code <=", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeLike(String value) {
			addCriterion("gift_code like", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeNotLike(String value) {
			addCriterion("gift_code not like", value, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeIn(List<String> values) {
			addCriterion("gift_code in", values, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeNotIn(List<String> values) {
			addCriterion("gift_code not in", values, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeBetween(String value1, String value2) {
			addCriterion("gift_code between", value1, value2, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftCodeNotBetween(String value1, String value2) {
			addCriterion("gift_code not between", value1, value2, "giftCode");
			return (Criteria) this;
		}

		public Criteria andGiftNameIsNull() {
			addCriterion("gift_name is null");
			return (Criteria) this;
		}

		public Criteria andGiftNameIsNotNull() {
			addCriterion("gift_name is not null");
			return (Criteria) this;
		}

		public Criteria andGiftNameEqualTo(String value) {
			addCriterion("gift_name =", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameNotEqualTo(String value) {
			addCriterion("gift_name <>", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameGreaterThan(String value) {
			addCriterion("gift_name >", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameGreaterThanOrEqualTo(String value) {
			addCriterion("gift_name >=", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameLessThan(String value) {
			addCriterion("gift_name <", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameLessThanOrEqualTo(String value) {
			addCriterion("gift_name <=", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameLike(String value) {
			addCriterion("gift_name like", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameNotLike(String value) {
			addCriterion("gift_name not like", value, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameIn(List<String> values) {
			addCriterion("gift_name in", values, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameNotIn(List<String> values) {
			addCriterion("gift_name not in", values, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameBetween(String value1, String value2) {
			addCriterion("gift_name between", value1, value2, "giftName");
			return (Criteria) this;
		}

		public Criteria andGiftNameNotBetween(String value1, String value2) {
			addCriterion("gift_name not between", value1, value2, "giftName");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("channel is null");
			return (Criteria) this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("channel is not null");
			return (Criteria) this;
		}

		public Criteria andChannelEqualTo(String value) {
			addCriterion("channel =", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotEqualTo(String value) {
			addCriterion("channel <>", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThan(String value) {
			addCriterion("channel >", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(String value) {
			addCriterion("channel >=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThan(String value) {
			addCriterion("channel <", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThanOrEqualTo(String value) {
			addCriterion("channel <=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLike(String value) {
			addCriterion("channel like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotLike(String value) {
			addCriterion("channel not like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelIn(List<String> values) {
			addCriterion("channel in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotIn(List<String> values) {
			addCriterion("channel not in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelBetween(String value1, String value2) {
			addCriterion("channel between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotBetween(String value1, String value2) {
			addCriterion("channel not between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andCookieIsNull() {
			addCriterion("cookie is null");
			return (Criteria) this;
		}

		public Criteria andCookieIsNotNull() {
			addCriterion("cookie is not null");
			return (Criteria) this;
		}

		public Criteria andCookieEqualTo(String value) {
			addCriterion("cookie =", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotEqualTo(String value) {
			addCriterion("cookie <>", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieGreaterThan(String value) {
			addCriterion("cookie >", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieGreaterThanOrEqualTo(String value) {
			addCriterion("cookie >=", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieLessThan(String value) {
			addCriterion("cookie <", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieLessThanOrEqualTo(String value) {
			addCriterion("cookie <=", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieLike(String value) {
			addCriterion("cookie like", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotLike(String value) {
			addCriterion("cookie not like", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieIn(List<String> values) {
			addCriterion("cookie in", values, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotIn(List<String> values) {
			addCriterion("cookie not in", values, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieBetween(String value1, String value2) {
			addCriterion("cookie between", value1, value2, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotBetween(String value1, String value2) {
			addCriterion("cookie not between", value1, value2, "cookie");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderIsNull() {
			addCriterion("customer_gender is null");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderIsNotNull() {
			addCriterion("customer_gender is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderEqualTo(Integer value) {
			addCriterion("customer_gender =", value, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderNotEqualTo(Integer value) {
			addCriterion("customer_gender <>", value, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderGreaterThan(Integer value) {
			addCriterion("customer_gender >", value, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderGreaterThanOrEqualTo(Integer value) {
			addCriterion("customer_gender >=", value, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderLessThan(Integer value) {
			addCriterion("customer_gender <", value, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderLessThanOrEqualTo(Integer value) {
			addCriterion("customer_gender <=", value, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderIn(List<Integer> values) {
			addCriterion("customer_gender in", values, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderNotIn(List<Integer> values) {
			addCriterion("customer_gender not in", values, "customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderBetween(Integer value1, Integer value2) {
			addCriterion("customer_gender between", value1, value2,
					"customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerGenderNotBetween(Integer value1,
				Integer value2) {
			addCriterion("customer_gender not between", value1, value2,
					"customerGender");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusIsNull() {
			addCriterion("customer_status is null");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusIsNotNull() {
			addCriterion("customer_status is not null");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusEqualTo(Integer value) {
			addCriterion("customer_status =", value, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusNotEqualTo(Integer value) {
			addCriterion("customer_status <>", value, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusGreaterThan(Integer value) {
			addCriterion("customer_status >", value, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("customer_status >=", value, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusLessThan(Integer value) {
			addCriterion("customer_status <", value, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusLessThanOrEqualTo(Integer value) {
			addCriterion("customer_status <=", value, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusIn(List<Integer> values) {
			addCriterion("customer_status in", values, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusNotIn(List<Integer> values) {
			addCriterion("customer_status not in", values, "customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusBetween(Integer value1, Integer value2) {
			addCriterion("customer_status between", value1, value2,
					"customerStatus");
			return (Criteria) this;
		}

		public Criteria andCustomerStatusNotBetween(Integer value1,
				Integer value2) {
			addCriterion("customer_status not between", value1, value2,
					"customerStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table appointment
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appointment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}