package cn.lby.entity;

import java.util.Date;

public class AppointmentLoginManage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_login_manage.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_login_manage.token
	 * @mbggenerated
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_login_manage.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appointment_login_manage.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_login_manage.mobile
	 * @return  the value of appointment_login_manage.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_login_manage.mobile
	 * @param mobile  the value for appointment_login_manage.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_login_manage.token
	 * @return  the value of appointment_login_manage.token
	 * @mbggenerated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_login_manage.token
	 * @param token  the value for appointment_login_manage.token
	 * @mbggenerated
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_login_manage.status
	 * @return  the value of appointment_login_manage.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_login_manage.status
	 * @param status  the value for appointment_login_manage.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appointment_login_manage.create_time
	 * @return  the value of appointment_login_manage.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appointment_login_manage.create_time
	 * @param createTime  the value for appointment_login_manage.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}