package cn.lby.entity;

import java.util.Date;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.code
	 * @mbggenerated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.gender
	 * @mbggenerated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.id_card
	 * @mbggenerated
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.drive_age
	 * @mbggenerated
	 */
	private Integer driveAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.birthday
	 * @mbggenerated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.is_married
	 * @mbggenerated
	 */
	private Integer isMarried;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.profession
	 * @mbggenerated
	 */
	private Integer profession;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.driving_license
	 * @mbggenerated
	 */
	private String drivingLicense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.dmc_id
	 * @mbggenerated
	 */
	private String dmcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.cookie
	 * @mbggenerated
	 */
	private String cookie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.wechat_name
	 * @mbggenerated
	 */
	private String wechatName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.id
	 * @return  the value of customer.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.id
	 * @param id  the value for customer.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.code
	 * @return  the value of customer.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.code
	 * @param code  the value for customer.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.name
	 * @return  the value of customer.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.name
	 * @param name  the value for customer.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.gender
	 * @return  the value of customer.gender
	 * @mbggenerated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.gender
	 * @param gender  the value for customer.gender
	 * @mbggenerated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.mobile
	 * @return  the value of customer.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.mobile
	 * @param mobile  the value for customer.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.email
	 * @return  the value of customer.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.email
	 * @param email  the value for customer.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.address
	 * @return  the value of customer.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.address
	 * @param address  the value for customer.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.id_card
	 * @return  the value of customer.id_card
	 * @mbggenerated
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.id_card
	 * @param idCard  the value for customer.id_card
	 * @mbggenerated
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard == null ? null : idCard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.drive_age
	 * @return  the value of customer.drive_age
	 * @mbggenerated
	 */
	public Integer getDriveAge() {
		return driveAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.drive_age
	 * @param driveAge  the value for customer.drive_age
	 * @mbggenerated
	 */
	public void setDriveAge(Integer driveAge) {
		this.driveAge = driveAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.birthday
	 * @return  the value of customer.birthday
	 * @mbggenerated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.birthday
	 * @param birthday  the value for customer.birthday
	 * @mbggenerated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.is_married
	 * @return  the value of customer.is_married
	 * @mbggenerated
	 */
	public Integer getIsMarried() {
		return isMarried;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.is_married
	 * @param isMarried  the value for customer.is_married
	 * @mbggenerated
	 */
	public void setIsMarried(Integer isMarried) {
		this.isMarried = isMarried;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.profession
	 * @return  the value of customer.profession
	 * @mbggenerated
	 */
	public Integer getProfession() {
		return profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.profession
	 * @param profession  the value for customer.profession
	 * @mbggenerated
	 */
	public void setProfession(Integer profession) {
		this.profession = profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.driving_license
	 * @return  the value of customer.driving_license
	 * @mbggenerated
	 */
	public String getDrivingLicense() {
		return drivingLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.driving_license
	 * @param drivingLicense  the value for customer.driving_license
	 * @mbggenerated
	 */
	public void setDrivingLicense(String drivingLicense) {
		this.drivingLicense = drivingLicense == null ? null : drivingLicense
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.status
	 * @return  the value of customer.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.status
	 * @param status  the value for customer.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.create_time
	 * @return  the value of customer.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.create_time
	 * @param createTime  the value for customer.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.dmc_id
	 * @return  the value of customer.dmc_id
	 * @mbggenerated
	 */
	public String getDmcId() {
		return dmcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.dmc_id
	 * @param dmcId  the value for customer.dmc_id
	 * @mbggenerated
	 */
	public void setDmcId(String dmcId) {
		this.dmcId = dmcId == null ? null : dmcId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.cookie
	 * @return  the value of customer.cookie
	 * @mbggenerated
	 */
	public String getCookie() {
		return cookie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.cookie
	 * @param cookie  the value for customer.cookie
	 * @mbggenerated
	 */
	public void setCookie(String cookie) {
		this.cookie = cookie == null ? null : cookie.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.wechat_name
	 * @return  the value of customer.wechat_name
	 * @mbggenerated
	 */
	public String getWechatName() {
		return wechatName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.wechat_name
	 * @param wechatName  the value for customer.wechat_name
	 * @mbggenerated
	 */
	public void setWechatName(String wechatName) {
		this.wechatName = wechatName == null ? null : wechatName.trim();
	}
}