package cn.lby.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customer
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customer
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table customer
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public CustomerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customer
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Integer value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Integer value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Integer value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Integer value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Integer value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Integer> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Integer> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Integer value1, Integer value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Integer value1, Integer value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNull() {
			addCriterion("id_card is null");
			return (Criteria) this;
		}

		public Criteria andIdCardIsNotNull() {
			addCriterion("id_card is not null");
			return (Criteria) this;
		}

		public Criteria andIdCardEqualTo(String value) {
			addCriterion("id_card =", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotEqualTo(String value) {
			addCriterion("id_card <>", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThan(String value) {
			addCriterion("id_card >", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardGreaterThanOrEqualTo(String value) {
			addCriterion("id_card >=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThan(String value) {
			addCriterion("id_card <", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLessThanOrEqualTo(String value) {
			addCriterion("id_card <=", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardLike(String value) {
			addCriterion("id_card like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotLike(String value) {
			addCriterion("id_card not like", value, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardIn(List<String> values) {
			addCriterion("id_card in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotIn(List<String> values) {
			addCriterion("id_card not in", values, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardBetween(String value1, String value2) {
			addCriterion("id_card between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andIdCardNotBetween(String value1, String value2) {
			addCriterion("id_card not between", value1, value2, "idCard");
			return (Criteria) this;
		}

		public Criteria andDriveAgeIsNull() {
			addCriterion("drive_age is null");
			return (Criteria) this;
		}

		public Criteria andDriveAgeIsNotNull() {
			addCriterion("drive_age is not null");
			return (Criteria) this;
		}

		public Criteria andDriveAgeEqualTo(Integer value) {
			addCriterion("drive_age =", value, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeNotEqualTo(Integer value) {
			addCriterion("drive_age <>", value, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeGreaterThan(Integer value) {
			addCriterion("drive_age >", value, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("drive_age >=", value, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeLessThan(Integer value) {
			addCriterion("drive_age <", value, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeLessThanOrEqualTo(Integer value) {
			addCriterion("drive_age <=", value, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeIn(List<Integer> values) {
			addCriterion("drive_age in", values, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeNotIn(List<Integer> values) {
			addCriterion("drive_age not in", values, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeBetween(Integer value1, Integer value2) {
			addCriterion("drive_age between", value1, value2, "driveAge");
			return (Criteria) this;
		}

		public Criteria andDriveAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("drive_age not between", value1, value2, "driveAge");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterion("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterion("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterion("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterion("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterion("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterion("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterion("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterion("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterion("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterion("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andIsMarriedIsNull() {
			addCriterion("is_married is null");
			return (Criteria) this;
		}

		public Criteria andIsMarriedIsNotNull() {
			addCriterion("is_married is not null");
			return (Criteria) this;
		}

		public Criteria andIsMarriedEqualTo(Integer value) {
			addCriterion("is_married =", value, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedNotEqualTo(Integer value) {
			addCriterion("is_married <>", value, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedGreaterThan(Integer value) {
			addCriterion("is_married >", value, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_married >=", value, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedLessThan(Integer value) {
			addCriterion("is_married <", value, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedLessThanOrEqualTo(Integer value) {
			addCriterion("is_married <=", value, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedIn(List<Integer> values) {
			addCriterion("is_married in", values, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedNotIn(List<Integer> values) {
			addCriterion("is_married not in", values, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedBetween(Integer value1, Integer value2) {
			addCriterion("is_married between", value1, value2, "isMarried");
			return (Criteria) this;
		}

		public Criteria andIsMarriedNotBetween(Integer value1, Integer value2) {
			addCriterion("is_married not between", value1, value2, "isMarried");
			return (Criteria) this;
		}

		public Criteria andProfessionIsNull() {
			addCriterion("profession is null");
			return (Criteria) this;
		}

		public Criteria andProfessionIsNotNull() {
			addCriterion("profession is not null");
			return (Criteria) this;
		}

		public Criteria andProfessionEqualTo(Integer value) {
			addCriterion("profession =", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotEqualTo(Integer value) {
			addCriterion("profession <>", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionGreaterThan(Integer value) {
			addCriterion("profession >", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionGreaterThanOrEqualTo(Integer value) {
			addCriterion("profession >=", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLessThan(Integer value) {
			addCriterion("profession <", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLessThanOrEqualTo(Integer value) {
			addCriterion("profession <=", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionIn(List<Integer> values) {
			addCriterion("profession in", values, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotIn(List<Integer> values) {
			addCriterion("profession not in", values, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionBetween(Integer value1, Integer value2) {
			addCriterion("profession between", value1, value2, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotBetween(Integer value1, Integer value2) {
			addCriterion("profession not between", value1, value2, "profession");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseIsNull() {
			addCriterion("driving_license is null");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseIsNotNull() {
			addCriterion("driving_license is not null");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseEqualTo(String value) {
			addCriterion("driving_license =", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseNotEqualTo(String value) {
			addCriterion("driving_license <>", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseGreaterThan(String value) {
			addCriterion("driving_license >", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseGreaterThanOrEqualTo(String value) {
			addCriterion("driving_license >=", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseLessThan(String value) {
			addCriterion("driving_license <", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseLessThanOrEqualTo(String value) {
			addCriterion("driving_license <=", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseLike(String value) {
			addCriterion("driving_license like", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseNotLike(String value) {
			addCriterion("driving_license not like", value, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseIn(List<String> values) {
			addCriterion("driving_license in", values, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseNotIn(List<String> values) {
			addCriterion("driving_license not in", values, "drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseBetween(String value1, String value2) {
			addCriterion("driving_license between", value1, value2,
					"drivingLicense");
			return (Criteria) this;
		}

		public Criteria andDrivingLicenseNotBetween(String value1, String value2) {
			addCriterion("driving_license not between", value1, value2,
					"drivingLicense");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andDmcIdIsNull() {
			addCriterion("dmc_id is null");
			return (Criteria) this;
		}

		public Criteria andDmcIdIsNotNull() {
			addCriterion("dmc_id is not null");
			return (Criteria) this;
		}

		public Criteria andDmcIdEqualTo(String value) {
			addCriterion("dmc_id =", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdNotEqualTo(String value) {
			addCriterion("dmc_id <>", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdGreaterThan(String value) {
			addCriterion("dmc_id >", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdGreaterThanOrEqualTo(String value) {
			addCriterion("dmc_id >=", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdLessThan(String value) {
			addCriterion("dmc_id <", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdLessThanOrEqualTo(String value) {
			addCriterion("dmc_id <=", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdLike(String value) {
			addCriterion("dmc_id like", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdNotLike(String value) {
			addCriterion("dmc_id not like", value, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdIn(List<String> values) {
			addCriterion("dmc_id in", values, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdNotIn(List<String> values) {
			addCriterion("dmc_id not in", values, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdBetween(String value1, String value2) {
			addCriterion("dmc_id between", value1, value2, "dmcId");
			return (Criteria) this;
		}

		public Criteria andDmcIdNotBetween(String value1, String value2) {
			addCriterion("dmc_id not between", value1, value2, "dmcId");
			return (Criteria) this;
		}

		public Criteria andCookieIsNull() {
			addCriterion("cookie is null");
			return (Criteria) this;
		}

		public Criteria andCookieIsNotNull() {
			addCriterion("cookie is not null");
			return (Criteria) this;
		}

		public Criteria andCookieEqualTo(String value) {
			addCriterion("cookie =", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotEqualTo(String value) {
			addCriterion("cookie <>", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieGreaterThan(String value) {
			addCriterion("cookie >", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieGreaterThanOrEqualTo(String value) {
			addCriterion("cookie >=", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieLessThan(String value) {
			addCriterion("cookie <", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieLessThanOrEqualTo(String value) {
			addCriterion("cookie <=", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieLike(String value) {
			addCriterion("cookie like", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotLike(String value) {
			addCriterion("cookie not like", value, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieIn(List<String> values) {
			addCriterion("cookie in", values, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotIn(List<String> values) {
			addCriterion("cookie not in", values, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieBetween(String value1, String value2) {
			addCriterion("cookie between", value1, value2, "cookie");
			return (Criteria) this;
		}

		public Criteria andCookieNotBetween(String value1, String value2) {
			addCriterion("cookie not between", value1, value2, "cookie");
			return (Criteria) this;
		}

		public Criteria andWechatNameIsNull() {
			addCriterion("wechat_name is null");
			return (Criteria) this;
		}

		public Criteria andWechatNameIsNotNull() {
			addCriterion("wechat_name is not null");
			return (Criteria) this;
		}

		public Criteria andWechatNameEqualTo(String value) {
			addCriterion("wechat_name =", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameNotEqualTo(String value) {
			addCriterion("wechat_name <>", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameGreaterThan(String value) {
			addCriterion("wechat_name >", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameGreaterThanOrEqualTo(String value) {
			addCriterion("wechat_name >=", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameLessThan(String value) {
			addCriterion("wechat_name <", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameLessThanOrEqualTo(String value) {
			addCriterion("wechat_name <=", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameLike(String value) {
			addCriterion("wechat_name like", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameNotLike(String value) {
			addCriterion("wechat_name not like", value, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameIn(List<String> values) {
			addCriterion("wechat_name in", values, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameNotIn(List<String> values) {
			addCriterion("wechat_name not in", values, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameBetween(String value1, String value2) {
			addCriterion("wechat_name between", value1, value2, "wechatName");
			return (Criteria) this;
		}

		public Criteria andWechatNameNotBetween(String value1, String value2) {
			addCriterion("wechat_name not between", value1, value2,
					"wechatName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table customer
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}