package cn.lby.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MarketActivityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table market_activity
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table market_activity
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table market_activity
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public MarketActivityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table market_activity
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNull() {
			addCriterion("start_date is null");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNotNull() {
			addCriterion("start_date is not null");
			return (Criteria) this;
		}

		public Criteria andStartDateEqualTo(Date value) {
			addCriterionForJDBCDate("start_date =", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("start_date <>", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThan(Date value) {
			addCriterionForJDBCDate("start_date >", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_date >=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThan(Date value) {
			addCriterionForJDBCDate("start_date <", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_date <=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateIn(List<Date> values) {
			addCriterionForJDBCDate("start_date in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("start_date not in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_date between", value1, value2,
					"startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_date not between", value1, value2,
					"startDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterionForJDBCDate("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterionForJDBCDate("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterionForJDBCDate("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterionForJDBCDate("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date between", value1, value2,
					"endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_date not between", value1, value2,
					"endDate");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdIsNull() {
			addCriterion("manufacturer_id is null");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdIsNotNull() {
			addCriterion("manufacturer_id is not null");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdEqualTo(String value) {
			addCriterion("manufacturer_id =", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotEqualTo(String value) {
			addCriterion("manufacturer_id <>", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdGreaterThan(String value) {
			addCriterion("manufacturer_id >", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdGreaterThanOrEqualTo(String value) {
			addCriterion("manufacturer_id >=", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdLessThan(String value) {
			addCriterion("manufacturer_id <", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdLessThanOrEqualTo(String value) {
			addCriterion("manufacturer_id <=", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdLike(String value) {
			addCriterion("manufacturer_id like", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotLike(String value) {
			addCriterion("manufacturer_id not like", value, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdIn(List<String> values) {
			addCriterion("manufacturer_id in", values, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotIn(List<String> values) {
			addCriterion("manufacturer_id not in", values, "manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdBetween(String value1, String value2) {
			addCriterion("manufacturer_id between", value1, value2,
					"manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerIdNotBetween(String value1, String value2) {
			addCriterion("manufacturer_id not between", value1, value2,
					"manufacturerId");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameIsNull() {
			addCriterion("manufacturer_name is null");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameIsNotNull() {
			addCriterion("manufacturer_name is not null");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameEqualTo(String value) {
			addCriterion("manufacturer_name =", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameNotEqualTo(String value) {
			addCriterion("manufacturer_name <>", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameGreaterThan(String value) {
			addCriterion("manufacturer_name >", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameGreaterThanOrEqualTo(String value) {
			addCriterion("manufacturer_name >=", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameLessThan(String value) {
			addCriterion("manufacturer_name <", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameLessThanOrEqualTo(String value) {
			addCriterion("manufacturer_name <=", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameLike(String value) {
			addCriterion("manufacturer_name like", value, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameNotLike(String value) {
			addCriterion("manufacturer_name not like", value,
					"manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameIn(List<String> values) {
			addCriterion("manufacturer_name in", values, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameNotIn(List<String> values) {
			addCriterion("manufacturer_name not in", values, "manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameBetween(String value1, String value2) {
			addCriterion("manufacturer_name between", value1, value2,
					"manufacturerName");
			return (Criteria) this;
		}

		public Criteria andManufacturerNameNotBetween(String value1,
				String value2) {
			addCriterion("manufacturer_name not between", value1, value2,
					"manufacturerName");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("brand_id is null");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("brand_id is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIdEqualTo(String value) {
			addCriterion("brand_id =", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotEqualTo(String value) {
			addCriterion("brand_id <>", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThan(String value) {
			addCriterion("brand_id >", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(String value) {
			addCriterion("brand_id >=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThan(String value) {
			addCriterion("brand_id <", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(String value) {
			addCriterion("brand_id <=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLike(String value) {
			addCriterion("brand_id like", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotLike(String value) {
			addCriterion("brand_id not like", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdIn(List<String> values) {
			addCriterion("brand_id in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotIn(List<String> values) {
			addCriterion("brand_id not in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdBetween(String value1, String value2) {
			addCriterion("brand_id between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotBetween(String value1, String value2) {
			addCriterion("brand_id not between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandCodeIsNull() {
			addCriterion("brand_code is null");
			return (Criteria) this;
		}

		public Criteria andBrandCodeIsNotNull() {
			addCriterion("brand_code is not null");
			return (Criteria) this;
		}

		public Criteria andBrandCodeEqualTo(String value) {
			addCriterion("brand_code =", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotEqualTo(String value) {
			addCriterion("brand_code <>", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeGreaterThan(String value) {
			addCriterion("brand_code >", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeGreaterThanOrEqualTo(String value) {
			addCriterion("brand_code >=", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeLessThan(String value) {
			addCriterion("brand_code <", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeLessThanOrEqualTo(String value) {
			addCriterion("brand_code <=", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeLike(String value) {
			addCriterion("brand_code like", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotLike(String value) {
			addCriterion("brand_code not like", value, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeIn(List<String> values) {
			addCriterion("brand_code in", values, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotIn(List<String> values) {
			addCriterion("brand_code not in", values, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeBetween(String value1, String value2) {
			addCriterion("brand_code between", value1, value2, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandCodeNotBetween(String value1, String value2) {
			addCriterion("brand_code not between", value1, value2, "brandCode");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("brand_name is null");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("brand_name is not null");
			return (Criteria) this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("brand_name =", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("brand_name <>", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("brand_name >", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("brand_name >=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("brand_name <", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("brand_name <=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("brand_name like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("brand_name not like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameIn(List<String> values) {
			addCriterion("brand_name in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotIn(List<String> values) {
			addCriterion("brand_name not in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("brand_name between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("brand_name not between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andActivityAddressIsNull() {
			addCriterion("activity_address is null");
			return (Criteria) this;
		}

		public Criteria andActivityAddressIsNotNull() {
			addCriterion("activity_address is not null");
			return (Criteria) this;
		}

		public Criteria andActivityAddressEqualTo(String value) {
			addCriterion("activity_address =", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressNotEqualTo(String value) {
			addCriterion("activity_address <>", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressGreaterThan(String value) {
			addCriterion("activity_address >", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressGreaterThanOrEqualTo(String value) {
			addCriterion("activity_address >=", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressLessThan(String value) {
			addCriterion("activity_address <", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressLessThanOrEqualTo(String value) {
			addCriterion("activity_address <=", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressLike(String value) {
			addCriterion("activity_address like", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressNotLike(String value) {
			addCriterion("activity_address not like", value, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressIn(List<String> values) {
			addCriterion("activity_address in", values, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressNotIn(List<String> values) {
			addCriterion("activity_address not in", values, "activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressBetween(String value1, String value2) {
			addCriterion("activity_address between", value1, value2,
					"activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityAddressNotBetween(String value1,
				String value2) {
			addCriterion("activity_address not between", value1, value2,
					"activityAddress");
			return (Criteria) this;
		}

		public Criteria andActivityTimeIsNull() {
			addCriterion("activity_time is null");
			return (Criteria) this;
		}

		public Criteria andActivityTimeIsNotNull() {
			addCriterion("activity_time is not null");
			return (Criteria) this;
		}

		public Criteria andActivityTimeEqualTo(String value) {
			addCriterion("activity_time =", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeNotEqualTo(String value) {
			addCriterion("activity_time <>", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeGreaterThan(String value) {
			addCriterion("activity_time >", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeGreaterThanOrEqualTo(String value) {
			addCriterion("activity_time >=", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeLessThan(String value) {
			addCriterion("activity_time <", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeLessThanOrEqualTo(String value) {
			addCriterion("activity_time <=", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeLike(String value) {
			addCriterion("activity_time like", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeNotLike(String value) {
			addCriterion("activity_time not like", value, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeIn(List<String> values) {
			addCriterion("activity_time in", values, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeNotIn(List<String> values) {
			addCriterion("activity_time not in", values, "activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeBetween(String value1, String value2) {
			addCriterion("activity_time between", value1, value2,
					"activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityTimeNotBetween(String value1, String value2) {
			addCriterion("activity_time not between", value1, value2,
					"activityTime");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneIsNull() {
			addCriterion("activity_contact_phone is null");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneIsNotNull() {
			addCriterion("activity_contact_phone is not null");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneEqualTo(String value) {
			addCriterion("activity_contact_phone =", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneNotEqualTo(String value) {
			addCriterion("activity_contact_phone <>", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneGreaterThan(String value) {
			addCriterion("activity_contact_phone >", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("activity_contact_phone >=", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneLessThan(String value) {
			addCriterion("activity_contact_phone <", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneLessThanOrEqualTo(String value) {
			addCriterion("activity_contact_phone <=", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneLike(String value) {
			addCriterion("activity_contact_phone like", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneNotLike(String value) {
			addCriterion("activity_contact_phone not like", value,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneIn(List<String> values) {
			addCriterion("activity_contact_phone in", values,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneNotIn(List<String> values) {
			addCriterion("activity_contact_phone not in", values,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneBetween(String value1,
				String value2) {
			addCriterion("activity_contact_phone between", value1, value2,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andActivityContactPhoneNotBetween(String value1,
				String value2) {
			addCriterion("activity_contact_phone not between", value1, value2,
					"activityContactPhone");
			return (Criteria) this;
		}

		public Criteria andProvinceIdIsNull() {
			addCriterion("province_id is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIdIsNotNull() {
			addCriterion("province_id is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceIdEqualTo(String value) {
			addCriterion("province_id =", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotEqualTo(String value) {
			addCriterion("province_id <>", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdGreaterThan(String value) {
			addCriterion("province_id >", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdGreaterThanOrEqualTo(String value) {
			addCriterion("province_id >=", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdLessThan(String value) {
			addCriterion("province_id <", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdLessThanOrEqualTo(String value) {
			addCriterion("province_id <=", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdLike(String value) {
			addCriterion("province_id like", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotLike(String value) {
			addCriterion("province_id not like", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdIn(List<String> values) {
			addCriterion("province_id in", values, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotIn(List<String> values) {
			addCriterion("province_id not in", values, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdBetween(String value1, String value2) {
			addCriterion("province_id between", value1, value2, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotBetween(String value1, String value2) {
			addCriterion("province_id not between", value1, value2,
					"provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceNameIsNull() {
			addCriterion("province_name is null");
			return (Criteria) this;
		}

		public Criteria andProvinceNameIsNotNull() {
			addCriterion("province_name is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceNameEqualTo(String value) {
			addCriterion("province_name =", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameNotEqualTo(String value) {
			addCriterion("province_name <>", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameGreaterThan(String value) {
			addCriterion("province_name >", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
			addCriterion("province_name >=", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameLessThan(String value) {
			addCriterion("province_name <", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameLessThanOrEqualTo(String value) {
			addCriterion("province_name <=", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameLike(String value) {
			addCriterion("province_name like", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameNotLike(String value) {
			addCriterion("province_name not like", value, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameIn(List<String> values) {
			addCriterion("province_name in", values, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameNotIn(List<String> values) {
			addCriterion("province_name not in", values, "provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameBetween(String value1, String value2) {
			addCriterion("province_name between", value1, value2,
					"provinceName");
			return (Criteria) this;
		}

		public Criteria andProvinceNameNotBetween(String value1, String value2) {
			addCriterion("province_name not between", value1, value2,
					"provinceName");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNull() {
			addCriterion("city_id is null");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNotNull() {
			addCriterion("city_id is not null");
			return (Criteria) this;
		}

		public Criteria andCityIdEqualTo(String value) {
			addCriterion("city_id =", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotEqualTo(String value) {
			addCriterion("city_id <>", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThan(String value) {
			addCriterion("city_id >", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThanOrEqualTo(String value) {
			addCriterion("city_id >=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThan(String value) {
			addCriterion("city_id <", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThanOrEqualTo(String value) {
			addCriterion("city_id <=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLike(String value) {
			addCriterion("city_id like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotLike(String value) {
			addCriterion("city_id not like", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdIn(List<String> values) {
			addCriterion("city_id in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotIn(List<String> values) {
			addCriterion("city_id not in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdBetween(String value1, String value2) {
			addCriterion("city_id between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotBetween(String value1, String value2) {
			addCriterion("city_id not between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNull() {
			addCriterion("city_name is null");
			return (Criteria) this;
		}

		public Criteria andCityNameIsNotNull() {
			addCriterion("city_name is not null");
			return (Criteria) this;
		}

		public Criteria andCityNameEqualTo(String value) {
			addCriterion("city_name =", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotEqualTo(String value) {
			addCriterion("city_name <>", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThan(String value) {
			addCriterion("city_name >", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameGreaterThanOrEqualTo(String value) {
			addCriterion("city_name >=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThan(String value) {
			addCriterion("city_name <", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLessThanOrEqualTo(String value) {
			addCriterion("city_name <=", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameLike(String value) {
			addCriterion("city_name like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotLike(String value) {
			addCriterion("city_name not like", value, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameIn(List<String> values) {
			addCriterion("city_name in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotIn(List<String> values) {
			addCriterion("city_name not in", values, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameBetween(String value1, String value2) {
			addCriterion("city_name between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andCityNameNotBetween(String value1, String value2) {
			addCriterion("city_name not between", value1, value2, "cityName");
			return (Criteria) this;
		}

		public Criteria andDistrictIdIsNull() {
			addCriterion("district_id is null");
			return (Criteria) this;
		}

		public Criteria andDistrictIdIsNotNull() {
			addCriterion("district_id is not null");
			return (Criteria) this;
		}

		public Criteria andDistrictIdEqualTo(String value) {
			addCriterion("district_id =", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotEqualTo(String value) {
			addCriterion("district_id <>", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdGreaterThan(String value) {
			addCriterion("district_id >", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdGreaterThanOrEqualTo(String value) {
			addCriterion("district_id >=", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdLessThan(String value) {
			addCriterion("district_id <", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdLessThanOrEqualTo(String value) {
			addCriterion("district_id <=", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdLike(String value) {
			addCriterion("district_id like", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotLike(String value) {
			addCriterion("district_id not like", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdIn(List<String> values) {
			addCriterion("district_id in", values, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotIn(List<String> values) {
			addCriterion("district_id not in", values, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdBetween(String value1, String value2) {
			addCriterion("district_id between", value1, value2, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotBetween(String value1, String value2) {
			addCriterion("district_id not between", value1, value2,
					"districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictNameIsNull() {
			addCriterion("district_name is null");
			return (Criteria) this;
		}

		public Criteria andDistrictNameIsNotNull() {
			addCriterion("district_name is not null");
			return (Criteria) this;
		}

		public Criteria andDistrictNameEqualTo(String value) {
			addCriterion("district_name =", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameNotEqualTo(String value) {
			addCriterion("district_name <>", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameGreaterThan(String value) {
			addCriterion("district_name >", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameGreaterThanOrEqualTo(String value) {
			addCriterion("district_name >=", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameLessThan(String value) {
			addCriterion("district_name <", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameLessThanOrEqualTo(String value) {
			addCriterion("district_name <=", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameLike(String value) {
			addCriterion("district_name like", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameNotLike(String value) {
			addCriterion("district_name not like", value, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameIn(List<String> values) {
			addCriterion("district_name in", values, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameNotIn(List<String> values) {
			addCriterion("district_name not in", values, "districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameBetween(String value1, String value2) {
			addCriterion("district_name between", value1, value2,
					"districtName");
			return (Criteria) this;
		}

		public Criteria andDistrictNameNotBetween(String value1, String value2) {
			addCriterion("district_name not between", value1, value2,
					"districtName");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeIsNull() {
			addCriterion("appointment_time is null");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeIsNotNull() {
			addCriterion("appointment_time is not null");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeEqualTo(Integer value) {
			addCriterion("appointment_time =", value, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeNotEqualTo(Integer value) {
			addCriterion("appointment_time <>", value, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeGreaterThan(Integer value) {
			addCriterion("appointment_time >", value, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("appointment_time >=", value, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeLessThan(Integer value) {
			addCriterion("appointment_time <", value, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeLessThanOrEqualTo(Integer value) {
			addCriterion("appointment_time <=", value, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeIn(List<Integer> values) {
			addCriterion("appointment_time in", values, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeNotIn(List<Integer> values) {
			addCriterion("appointment_time not in", values, "appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeBetween(Integer value1, Integer value2) {
			addCriterion("appointment_time between", value1, value2,
					"appointmentTime");
			return (Criteria) this;
		}

		public Criteria andAppointmentTimeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("appointment_time not between", value1, value2,
					"appointmentTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeIsNull() {
			addCriterion("limit_time is null");
			return (Criteria) this;
		}

		public Criteria andLimitTimeIsNotNull() {
			addCriterion("limit_time is not null");
			return (Criteria) this;
		}

		public Criteria andLimitTimeEqualTo(Integer value) {
			addCriterion("limit_time =", value, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeNotEqualTo(Integer value) {
			addCriterion("limit_time <>", value, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeGreaterThan(Integer value) {
			addCriterion("limit_time >", value, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("limit_time >=", value, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeLessThan(Integer value) {
			addCriterion("limit_time <", value, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeLessThanOrEqualTo(Integer value) {
			addCriterion("limit_time <=", value, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeIn(List<Integer> values) {
			addCriterion("limit_time in", values, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeNotIn(List<Integer> values) {
			addCriterion("limit_time not in", values, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeBetween(Integer value1, Integer value2) {
			addCriterion("limit_time between", value1, value2, "limitTime");
			return (Criteria) this;
		}

		public Criteria andLimitTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("limit_time not between", value1, value2, "limitTime");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressIsNull() {
			addCriterion("detail_activity_address is null");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressIsNotNull() {
			addCriterion("detail_activity_address is not null");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressEqualTo(String value) {
			addCriterion("detail_activity_address =", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressNotEqualTo(String value) {
			addCriterion("detail_activity_address <>", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressGreaterThan(String value) {
			addCriterion("detail_activity_address >", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressGreaterThanOrEqualTo(
				String value) {
			addCriterion("detail_activity_address >=", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressLessThan(String value) {
			addCriterion("detail_activity_address <", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressLessThanOrEqualTo(String value) {
			addCriterion("detail_activity_address <=", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressLike(String value) {
			addCriterion("detail_activity_address like", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressNotLike(String value) {
			addCriterion("detail_activity_address not like", value,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressIn(List<String> values) {
			addCriterion("detail_activity_address in", values,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressNotIn(List<String> values) {
			addCriterion("detail_activity_address not in", values,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressBetween(String value1,
				String value2) {
			addCriterion("detail_activity_address between", value1, value2,
					"detailActivityAddress");
			return (Criteria) this;
		}

		public Criteria andDetailActivityAddressNotBetween(String value1,
				String value2) {
			addCriterion("detail_activity_address not between", value1, value2,
					"detailActivityAddress");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table market_activity
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table market_activity
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}